import { Metadata } from "next"
import Link from "next/link"
import { ArrowLeft } from "lucide-react"

export const metadata: Metadata = {
  title: "Terms of Service - Formatly",
  description: "Terms and conditions for using Formatly's AI-powered formatting services.",
}

export default function TermsOfServicePage() {
  const lastUpdated = "March 1, 2026"

  return (
    <div className="min-h-screen bg-background text-foreground py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        <div className="mb-8">
          <Link
            href="/"
            className="inline-flex items-center text-sm font-medium text-muted-foreground hover:text-primary transition-colors mb-6"
          >
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Home
          </Link>
          <h1 className="text-4xl font-extrabold tracking-tight text-foreground sm:text-5xl mb-4">
            Terms of Service
          </h1>
          <p className="text-lg text-muted-foreground">
            Last updated: {lastUpdated}
          </p>
        </div>

        <div className="prose prose-zinc dark:prose-invert max-w-none space-y-8">
          <section>
            <h2 className="text-2xl font-bold tracking-tight text-foreground border-b border-border pb-2 mb-4">
              1. Acceptance of Terms & Legally Binding Agreement
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              By accessing, registering for, or using the Formatly website, application, API, and associated services (collectively, the "Services"), you agree to be bound by these Terms of Service ("Terms"). If you are entering into these Terms on behalf of a company, organization, or another legal entity, you represent that you have the authority to bind such entity and its affiliates to these Terms. If you do not have such authority, or if you do not agree with these Terms, you must not accept these Terms and may not use the Services.
            </p>
            <p className="text-muted-foreground leading-relaxed mt-4">
              These Terms constitute a legally binding agreement between you (the "User") and Formatly Inc. ("we," "our," or "us"). We reserve the right to modify, amend, or update these Terms at any time. We will provide notice of material changes by posting the updated Terms on our website and updating the "Last updated" date. Your continued use of the Services following any such changes constitutes your binding acceptance of the revised Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold tracking-tight text-foreground border-b border-border pb-2 mb-4">
              2. Detailed Description of Service & AI Nature
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              Formatly provides a technology platform utilizing artificial intelligence, machine learning, and algorithmic parsing to automate the formatting of documents according to specific academic, organizational, and professional style guidelines (e.g., APA, MLA, Chicago, Custom Institutional Guides).
            </p>
            <p className="text-muted-foreground leading-relaxed mt-4">
              <strong>Beta Features and AI Output:</strong> You acknowledge that AI technology is inherently probabilistic and continuously evolving. As such, the outputs generated by the Services ("Output") may occasionally contain errors, inaccuracies, formatting anomalies, or incomplete transformations. You accept full responsibility for reviewing, verifying, and approving all Output before utilizing it for any submission, publication, professional, or academic purpose.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold tracking-tight text-foreground border-b border-border pb-2 mb-4">
              3. User Accounts, Security, and Responsibility
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              <strong>Account Creation:</strong> To access the full functionality of the Services, you must create an account. You agree to provide accurate, current, and complete information and to keep this information updated.
            </p>
            <ul className="list-disc pl-6 mt-4 space-y-2 text-muted-foreground">
              <li><strong>Account Security:</strong> You are strictly responsible for safeguarding your password, API keys, and any other authentication credentials used to access the Services. You agree not to disclose your password to any third party.</li>
              <li><strong>Liability for Account Activity:</strong> You assume sole responsibility for any and all activities or actions that occur under your account, whether or not you have authorized such activities. You must notify us immediately at support@formatly.com upon becoming aware of any breach of security or unauthorized use of your account.</li>
              <li><strong>Account Transfer:</strong> You may not assign, sell, or otherwise transfer your account to another party without our prior written consent.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold tracking-tight text-foreground border-b border-border pb-2 mb-4">
              4. Payment, Subscriptions, Refunds, and Taxes
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              <strong>Subscription Fees:</strong> Certain tiers of our Services require a paid subscription. By selecting a subscription plan, you agree to pay the applicable fees (monthly or annually) based on your selected tier. All fees are stated in U.S. Dollars and are exclusive of taxes unless otherwise explicitly stated.
            </p>
            <p className="text-muted-foreground leading-relaxed mt-4">
              <strong>Auto-Renewal:</strong> Subscriptions are billed in advance and automatically renew at the end of the applicable subscription period unless cancelled prior to the renewal date. You authorize Formatly (or our designated third-party payment processors, such as PayPal or Stripe) to charge your stored payment method for all renewal fees.
            </p>
             <p className="text-muted-foreground leading-relaxed mt-4">
              <strong>No Refunds Policy:</strong> Except as required by mandatory consumer protection laws, <strong>all payments are strictly non-refundable</strong>. There will be no refunds, prorated credits, or partial refunds for downgraded plans, unused time, or unused document quotas during an active subscription period.
            </p>
            <p className="text-muted-foreground leading-relaxed mt-4">
              <strong>Taxes:</strong> You are responsible for all applicable local, state, national, and international taxes, duties, and levies associated with your use of the Services, excluding taxes based on Formatly's net income.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold tracking-tight text-foreground border-b border-border pb-2 mb-4">
              5. Intellectual Property Rights & Document Ownership
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              <strong>Your Content (100% Retained Ownership):</strong> You retain full, sole, and exclusive ownership, copyright, and all related intellectual property rights to the documents, texts, drafts, datasets, and materials you upload, transmit, or process using the Service ("Your Content"). Formatly claims absolutely NO intellectual property rights or ownership stakes over Your Content.
            </p>
            <p className="text-muted-foreground leading-relaxed mt-4">
              <strong>License to Process:</strong> By uploading Your Content, you grant Formatly a limited, non-exclusive, worldwide, royalty-free, and strictly technical license to host, parse, analyze, modify (for formatting purposes only), and transmit Your Content solely for the explicit purpose of providing the styling and formatting Services to you.
            </p>
            <p className="text-muted-foreground leading-relaxed mt-4">
              <strong>Our Technology:</strong> The Formatly platform, including its original source code, AI algorithms, heuristics, parsers, visual design, UI/UX elements, logos, and documentation, are and will remain the exclusive intellectual property of Formatly Inc. and its licensors. You may not reverse-engineer, decompile, modify, distribute, or create derivative works based on our platform technology.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold tracking-tight text-foreground border-b border-border pb-2 mb-4">
              6. Comprehensive Acceptable Use Policy
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              You agree to use the Services only for lawful purposes. You represent, warrant, and agree that you will NOT use the Services to:
            </p>
            <ul className="list-disc pl-6 mt-4 space-y-2 text-muted-foreground">
              <li>Upload or process any content that infringes upon the intellectual property rights, privacy rights, or contractual rights of any third party.</li>
              <li>Upload documents containing malicious payloads, viruses, ransomware, trojans, worms, or any other code designed to disrupt, damage, or illegally extract data from our infrastructure.</li>
              <li>Attempt to bypass, disable, or defeat any security features, technical limitations, or access controls implemented within the Services.</li>
              <li>Use the Services to process Highly Sensitive Data (as defined by laws like HIPAA, unless a specific BAA is executed), unlawful materials, or content depicting child exploitation.</li>
              <li>Subject our infrastructure to unreasonable load through automated scraping, massive API floods without authorization, or denial-of-service tactics.</li>
              <li>Duplicate, resell, white-label, or act as an unauthorized service bureau offering Formatly's capabilities to third parties without an explicit Enterprise Agreement.</li>
            </ul>
             <p className="text-muted-foreground leading-relaxed mt-4">
              Formatly reserves the absolute right to audit compliance and immediately suspend or terminate accounts found violating this Acceptable Use Policy.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold tracking-tight text-foreground border-b border-border pb-2 mb-4">
              7. Academic Integrity & Plagiarism Disclaimer
            </h2>
            <p className="text-muted-foreground leading-relaxed">
               Formatly is a formatting and presentation tool, not a content generation, fact-checking, or plagiarism detection service.
            </p>
            <ul className="list-disc pl-6 mt-4 space-y-2 text-muted-foreground">
              <li><strong>No Content Verification:</strong> We do not verify the originality, factual accuracy, or academic validity of the text you upload.</li>
              <li><strong>Academic Policies:</strong> It is entirely your responsibility to ensure that your use of Formatly complies with the academic integrity policies, honor codes, or submission guidelines of your specific institution, publisher, or employer.</li>
              <li>Formatly shall not be held liable for any academic penalties, rejections, academic probation, or professional consequences resulting from your submission of documents formatted via our Services.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold tracking-tight text-foreground border-b border-border pb-2 mb-4">
              8. Limitation of Liability (Maximum Extent Permitted by Law)
            </h2>
            <p className="text-muted-foreground leading-relaxed uppercase font-semibold text-sm">
              Please read this section carefully as it severely limits our liability to you.
            </p>
            <p className="text-muted-foreground leading-relaxed mt-4">
              To the maximum extent permitted by applicable law, in no event shall Formatly Inc., its affiliates, directors, employees, agents, or licensors be liable for any indirect, punitive, incidental, special, consequential, or exemplary damages, including without limitation damages for loss of profits, revenue, goodwill, use, data, or other intangible losses, arising out of or relating to:
            </p>
            <ul className="list-disc pl-6 mt-4 space-y-2 text-muted-foreground">
               <li>Your use of, or inability to use, the Services.</li>
               <li>Any errors, mistakes, inaccuracies, or deviations in the formatted Output generated by the AI or heuristic parsers.</li>
               <li>Any unauthorized access to or use of our secure servers and/or any and all personal information stored therein.</li>
               <li>Any interruption, outage, or cessation of transmission to or from the Services.</li>
               <li>Any loss or corruption of your documents or data during transmission or processing.</li>
            </ul>
            <p className="text-muted-foreground leading-relaxed mt-4 font-bold text-foreground">
              Total Liability Cap: Under no circumstances will Formatly's total, aggregate liability to you for any and all claims arising out of or relating to these Terms or your use of the Services exceed the total amount you paid to Formatly for the Services in the three (3) months immediately preceding the event giving rise to the claim, or fifty U.S. dollars ($50.00), whichever is greater.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold tracking-tight text-foreground border-b border-border pb-2 mb-4">
              9. Warranties and Disclaimers
            </h2>
             <p className="text-muted-foreground leading-relaxed uppercase font-semibold text-sm">
              The services are provided "as is" and "as available."
            </p>
            <p className="text-muted-foreground leading-relaxed mt-4">
              Formatly Inc. expressly disclaims all warranties of any kind, whether express, implied, or statutory, including, but not limited to, the implied warranties of merchantability, fitness for a particular purpose, non-infringement, and any warranties arising out of course of dealing or usage of trade.
            </p>
            <p className="text-muted-foreground leading-relaxed mt-4">
              We make no warranty that (i) the Services will meet your strictly defined requirements, (ii) the Services will be 100% uninterrupted, timely, secure, or bug-free, or (iii) the AI-formatted output will perfectly match the edge-case requirements of complex municipal or academic rubrics without human review.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold tracking-tight text-foreground border-b border-border pb-2 mb-4">
              10. Indemnification
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              You agree to defend, indemnify, and hold harmless Formatly Inc., its officers, directors, employees, and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs, or debt, and expenses (including but not limited to reasonable attorney's fees) arising from:
            </p>
            <ul className="list-disc pl-6 mt-4 space-y-2 text-muted-foreground">
              <li>Your use of and access to the Services.</li>
              <li>Your violation of any term of these Terms of Service.</li>
              <li>Your violation of any third-party right, including without limitation any copyright, property, or privacy right.</li>
              <li>Any claim that Your Content caused damage to a third party.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold tracking-tight text-foreground border-b border-border pb-2 mb-4">
              11. Termination and Account Deletion
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              <strong>Termination by You:</strong> You may cancel your subscription and request account deletion at any time via the dashboard settings or by contacting support.
            </p>
            <p className="text-muted-foreground leading-relaxed mt-4">
              <strong>Termination by Us:</strong> We may terminate or suspend your account and bar access to the Services immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever and without limitation, including but not limited to a breach of the Terms.
            </p>
             <p className="text-muted-foreground leading-relaxed mt-4">
              <strong>Effect of Termination:</strong> Upon termination, your right to use the Services will immediately cease. All provisions of the Terms which by their nature should survive termination shall survive, including, without limitation, ownership provisions, warranty disclaimers, indemnity, and limitations of liability.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold tracking-tight text-foreground border-b border-border pb-2 mb-4">
              12. Governing Law, Venue, and Dispute Resolution
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              These Terms shall be governed by and construed strictly in accordance with the laws of the State of Delaware, United States, without regard to its conflict of law provisions.
            </p>
             <p className="text-muted-foreground leading-relaxed mt-4">
              <strong>Arbitration Agreement:</strong> Any dispute, controversy, or claim arising out of or relating to these Terms, including the formation, interpretation, breach, or termination thereof, including whether the claims asserted are arbitrable, will be referred to and finally determined by binding arbitration in accordance with the JAMS International Arbitration Rules. The tribunal will consist of a single arbitrator. The place of arbitration will be Wilmington, Delaware. The language to be used in the arbitral proceedings will be English.
            </p>
             <p className="text-muted-foreground leading-relaxed mt-4">
              <strong>Class Action Waiver:</strong> You and Formatly agree that any dispute resolution proceedings will be conducted only on an individual basis and not in a class, consolidated, or representative action.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold tracking-tight text-foreground border-b border-border pb-2 mb-4">
              13. Entire Agreement & Severability
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              These Terms, together with the Privacy Policy, constitute the entire, exclusive, and final statement of the agreement between you and Formatly regarding the Services, superseding any prior agreements. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in full force and effect.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold tracking-tight text-foreground border-b border-border pb-2 mb-4">
              14. Contact Information
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              For any legal notices, questions about these Terms, or formal correspondence, please contact our Legal Department:
            </p>
            <div className="mt-4 p-4 bg-muted/50 rounded-lg border border-border inline-block min-w-[300px]">
              <p className="font-medium text-foreground">Formatly Legal Department</p>
              <p className="text-sm mt-1 text-muted-foreground">ATTN: General Counsel</p>
              <p className="text-sm text-muted-foreground">Email: legal@formatly.com</p>
            </div>
          </section>
        </div>
      </div>
    </div>
  )
}
