-- Insert actual subscription plans with real data
INSERT INTO subscription_plans (
  id, name, description, price_monthly, price_yearly, currency, 
  features, document_limit, api_calls_limit, storage_limit_gb,
  priority_support, custom_styles, team_collaboration, is_popular, is_active
) VALUES 
(
  'free-plan',
  'Free',
  'Perfect for getting started with basic document formatting',
  0,
  0,
  'usd',
  ARRAY['Basic formatting', 'APA, MLA, Chicago styles', 'Email support'],
  5,
  100,
  1,
  false,
  false,
  false,
  false,
  true
),
(
  'pro-plan',
  'Pro',
  'Ideal for students and professionals with regular formatting needs',
  999,
  9990,
  'usd',
  ARRAY['Advanced formatting', 'All citation styles', 'Priority support', 'Custom templates', 'Batch processing'],
  100,
  5000,
  10,
  true,
  true,
  false,
  true,
  true
),
(
  'business-plan',
  'Business',
  'Perfect for teams and organizations with high-volume needs',
  2999,
  29990,
  'usd',
  ARRAY['Unlimited formatting', 'All citation styles', 'Priority support', 'Custom templates', 'Team collaboration', 'API access'],
  500,
  25000,
  50,
  true,
  true,
  true,
  false,
  true
),
(
  'enterprise-plan',
  'Enterprise',
  'Custom solution for large organizations with specific requirements',
  9999,
  99990,
  'usd',
  ARRAY['Unlimited everything', 'Custom integrations', 'Dedicated support', 'SLA guarantee', 'On-premise deployment'],
  -1,
  -1,
  -1,
  true,
  true,
  true,
  false,
  true
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  price_monthly = EXCLUDED.price_monthly,
  price_yearly = EXCLUDED.price_yearly,
  currency = EXCLUDED.currency,
  features = EXCLUDED.features,
  document_limit = EXCLUDED.document_limit,
  api_calls_limit = EXCLUDED.api_calls_limit,
  storage_limit_gb = EXCLUDED.storage_limit_gb,
  priority_support = EXCLUDED.priority_support,
  custom_styles = EXCLUDED.custom_styles,
  team_collaboration = EXCLUDED.team_collaboration,
  is_popular = EXCLUDED.is_popular,
  is_active = EXCLUDED.is_active,
  updated_at = NOW();
